### ISSUE TITLE
Error when running extension

### ISSUE THREAD

**Issue by lifeiscontent** [Divlo/vscode-styled-jsx#1]
[2020-10-14 16:47:52.613] [exthost] [error] [Divlo.vscode-styled-jsx-languageserver] provider FAILED
[2020-10-14 16:47:52.613] [exthost] [error] TypeError: Cannot read property 'map' of null
    at /Users/lifeiscontent/.vscode/extensions/divlo.vscode-styled-jsx-languageserver-1.0.0/client/out/extension.js:67:36
    at runNextTicks (internal/process/task_queues.js:59:5)
    at processImmediate (internal/timers.js:412:9)

**Comment by Divlo** [comment]
Hey, thanks for your report. Can you give some steps so I can reproduce ?

**Comment by lifeiscontent** [comment]
@Divlo i installed both and this was the log I got back after opening up VSCode with a styled-jsx component

**Comment by Divlo** [comment]
@lifeiscontent Weird, for me it's working...
Maybe you have another css related extension installed with VS Code ?
Can you show me screenshots of the styled-jsx component with the error please ?

**Comment by Divlo** [comment]
@lifeiscontent Any news since then ?

**Comment by lifeiscontent** [comment]
@Divlo hey! Sorry, I haven't been working in styled-jsx for a few weeks. If I get around to it again, I'll reopen the ticket, but for now let's close it. Sorry to waste your time.
