### ISSUE TITLE
Support css preprocessors

### ISSUE THREAD

**Issue by martonlederer** [Divlo/vscode-styled-jsx#13]
### Description
The plugin is missing support for css based languages, like `sass`, `scss`, `less`, `stylus`, etc.

### Describe the solution you'd like
Based on the babel configuration file, determinate which preprocessor the project is using and provide syntax highlighting for it.

**Comment by Divlo** [comment]
Thanks for your feedback!

We already have auto-completion for `scss`, thanks to this pull request #5, I don't know if it's also working for `less` and `stylus`.
Regarding syntax highlighting, indeed it's not working.
If you have any idea, how to do it, feel free to open a pull request, I would really appreciate it. 😃

**Comment by martonlederer** [comment]
Alright, I'll try to come up with something in the upcoming days :)

**Comment by martonlederer** [comment]
@Divlo I added you on discord, I have some ideas if you are up to collaborate

**Comment by Divlo** [comment]
Success, we now support SASS since this commit : https://github.com/Divlo/vscode-styled-jsx/commit/f72ea15fbd98b1d863973ff3a41560d2b4938ffe
