### ISSUE TITLE
Extension issue: Unresponsive; Too long Profile Time

### ISSUE THREAD

**Issue by angels101** [Divlo/vscode-styled-jsx#135]
- Issue Type: `Bug`
- Extension Name: `vscode-styled-jsx-languageserver`
- Extension Version: `1.3.0`
- OS Version: `Linux x64 5.8.0-63-generic`
- VS Code version: `1.63.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Divlo** [comment]
Hey! :wave: @angels101 
Thanks for your report!

Could you provide more information?
What is wrong, what is the issue?
