### ISSUE TITLE
Incompatible with postcss?

### ISSUE THREAD

**Issue by CallumJHays** [Divlo/vscode-styled-jsx#28]
Like #1 , I'm also running into the error:
```
[2021-01-09 17:54:08.426] [exthost] [error] TypeError: Cannot read property 'map' of null
	at /home/cal/.vscode/extensions/divlo.vscode-styled-jsx-languageserver-1.1.1/client/out/extension.js:52:36
```

It seems to be caused by the presence of a `postcss.config.js` file in the repo.
I've put together a minimum example of the bug here: 
https://github.com/CallumJHays/vscode-styled-jsx-provider-failure

cheers :beer:

**Comment by Divlo** [comment]
Thanks for your report! @CallumJHays 
I cloned your reproductible repo but I haven't got any errors, it is working fine.
Is it working without the `postcss.config.js` file ? Maybe you have another VSCode extension for `postcss` that conflicts with this one. If you have others clue so I can I reproduce, I would appreciate it.
![Capture1_35](https://user-images.githubusercontent.com/25207499/104088771-7604c580-5269-11eb-847a-48c28ea03a51.png)

**Comment by CallumJHays** [comment]
Okay, so the error only pops up when the postcss file is opened in a window. I've confirmed this is happening when *only* the Language Server extension is enabled. Probably a harmless error.
