### ISSUE TITLE
How to install this extension in VSCode

### ISSUE THREAD

**Issue by oyalhi** [Divlo/vscode-styled-jsx#29]
### Question
Thank you for taking these projects over and maintaining them. How do we install the extension to VSCode, can't find any link. Only found the un-maintained extension.

**Comment by Divlo** [comment]
Hey @oyalhi! 👋

### How to install ?

#### [styled-jsx Syntax Highlighting](https://marketplace.visualstudio.com/items?itemName=Divlo.vscode-styled-jsx-syntax)
Launch VS Code Quick Open (⌘+P), paste the following command, and press enter.
```
ext install Divlo.vscode-styled-jsx-syntax
```

#### [vscode-styled-jsx-languageserver](https://marketplace.visualstudio.com/items?itemName=Divlo.vscode-styled-jsx-languageserver)
Launch VS Code Quick Open (⌘+P), paste the following command, and press enter.
```
ext install Divlo.vscode-styled-jsx-languageserver
```

Do you think we should add this section in the `README`, maybe it wasn't intuitive enough ?

**Comment by oyalhi** [comment]
It does thank you.
