### ISSUE TITLE
Consider using `getSCSSLanguageService` instead of `getCSSLanguageService`?

### ISSUE THREAD

**Issue by u3u** [Divlo/vscode-styled-jsx#4]
### Type of Improvement :

- [ ] Files and Folders Structure
- [ ] Performance
- [ ] Refactoring code
- [ ] Tests
- [x] Not Sure?

### Proposal

https://github.com/Divlo/vscode-styled-jsx/blob/2d477b3c94cd324787ba7c33b67f945cc144326c/vscode-styled-jsx-languageserver/server/src/server.ts#L14

https://github.com/Divlo/vscode-styled-jsx/blob/2d477b3c94cd324787ba7c33b67f945cc144326c/vscode-styled-jsx-languageserver/server/src/server.ts#L25

Because `getSCSSLanguageService` supports nested syntax

```jsx
<style jsx>{`
  .btn {
    color: #333;

    // error: } expectedcss(css-rcurlyexpected)
    // error: at-rule or selector expectedcss(css-ruleorselectorexpected)
    &:hover {
      color: #000;
    }
  }
`}</style>
```

**Comment by Divlo** [comment]
Sure, that sounds good. Maybe you could do a pull-request ?
