### ISSUE TITLE
Conflict with linter

### ISSUE THREAD

**Issue by UnPolinomio** [Divlo/vscode-styled-jsx#60]
I'm getting the following error.

![](https://user-images.githubusercontent.com/42476070/115131139-4af1e680-9fbb-11eb-97f1-300818db774f.png)

I guess it's because \`} is not next to `</style>`

## Steps To Reproduce

1. Use the following jsx code:
```jsx
<style jsx>{`
    h1 {
      font-size: 1em;
    }
  `}
</style>
```

## The current behavior
It's causing a linting error.

## The expected behavior
I would expect not raising an error.

**Comment by Divlo** [comment]
Thanks for your report! @UnPolinomio 
It seems like I can't reproduce the issue :
![image](https://user-images.githubusercontent.com/25207499/115142939-9e5c4700-a044-11eb-89b8-b182346f3a04.png)

You can disable the VSCode CSS Linter by putting `"css.validate": false` inside `settings.json`.

**Comment by UnPolinomio** [comment]
I realized why this error is happening. I was using `andrewrazumovsky.vscode-styled-jsx-languageserver` extension, I switched to `divlo.vscode-styled-jsx-languageserver` and now the error is fixed.
Thanks for your help.

**Comment by Divlo** [comment]
Great that you succesfully fixed it,  feel free to give the repo a start, if you like it, thanks! :smile:
