### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by brianwachira** [Divlo/vscode-styled-jsx#61]
- Issue Type: `Performance`
- Extension Name: `vscode-styled-jsx-languageserver`
- Extension Version: `1.3.0`
- OS Version: `Linux x64 5.4.0-72-generic`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/Divlo.vscode-styled-jsx-languageserver-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Divlo** [comment]
Thanks for your report! @brianwachira 
Could you upload your `/tmp/Divlo.vscode-styled-jsx-languageserver-unresponsive.cpuprofile.txt` file.
If you know where it is coming from, feel free to open a PR. :smile: 
Personnaly, I'm running the extension fine without performance issue feeling, need to investigate.

**Comment by brianwachira** [comment]
Hi, Im trying to look for the file but I can't find it. Sorry for the inconvenience. Maybe I can close the issue?

**Comment by Divlo** [comment]
Hey, I don't know either where is this file so I'll close this issue for the moment but feel free to reopen it if you have others concerns about performance.

**Comment by brianwachira** [comment]
I definitely will. My machine keeps freezing mostly when I use vscode and I usually suspect its extensions. I use an i5
Anyway when I get the file I'll upload. 
Cheers!!!
